{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $root := . }}

{{- $app := .Values.app }}
{{- range $job := $app.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ print $release_name "-" $job.name | trunc 52 | trimSuffix "-" }}
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 10
  schedule: {{ $job.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: {{ $app.imagePullSecret }}
          containers:
          - name: {{ $job.name }}
            {{- if $job.image }}
            image: {{ $job.image }}
            {{- else }}
            image: {{ $app.image }}
            {{- end }}
            imagePullPolicy: {{ $job.pullPolicy }}
            {{- with $job.resources }}
            resources:
{{ toYaml . | indent 12 }}
              {{- end }}
            {{- if $job.command }}
            command: {{ $job.command }}
            {{- end }}
            {{- with $job.args }}
            args:
{{ toYaml . | indent 12 }}
              {{- end }}
            env:
              - name: DEPLOY_TIMESTAMP
                value: "{{ now | date "20060102150405" }}"
            {{- range $key, $value := $app.extraEnv }}
              - name: "{{ $key }}"
                value: "{{ $value }}"
            {{- end }}
            {{- range $secret := $app.extraSecretEnv }}
              {{- range $key, $value := $secret.fromSecret.data }}
              - name: {{ $key }}
                valueFrom:
                  secretKeyRef:
                      name: {{ $secret.fromSecret.name | quote }}
                      key: {{ $value | quote }}
              {{- end }}
            {{- end }}
            {{- range $key, $value := $job.extraEnv }}
              - name: "{{ $key }}"
                value: "{{ $value }}"
            {{- end }}
            {{- range $secret := $job.extraSecretEnv }}
              {{- range $key, $value := $secret.fromSecret.data }}
              - name: {{ $key }}
                valueFrom:
                  secretKeyRef:
                      name: {{ $secret.fromSecret.name | quote }}
                      key: {{ $value | quote }}
              {{- end }}
            {{- end }}
          restartPolicy: OnFailure
{{- end }}
