- name: Install charts
  hosts: bastion
  vars_files:
    - vars/bastion.yml
  tasks:
    - name: Add nginx charts repository
      kubernetes.core.helm_repository:
        name: stable
        repo_url: "https://kubernetes.github.io/ingress-nginx"

    - name: Add rancher charts repository
      kubernetes.core.helm_repository:
        name: rancher-stable
        repo_url: "https://releases.rancher.com/server-charts/stable"

    - name: Add jetstack charts repository
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"
