- name: Install pgpool II
  hosts: pgpool
  gather_facts: true
  become: true
  vars_files:
    - vars/pgpool.yml

  tasks:
    - name: Créer le fichier de position de pg pool
      ansible.builtin.copy:
        dest: /etc/pgpool2/pgpool_node_id
        content: "{{ index }}"
        mode: 0644

    - name: Créer le fichier .pgpoolkey dans le home de root
      ansible.builtin.copy:
        dest: /root/.pgpoolkey
        content: "{{ pgpoolkey }}"
        mode: 0600
        owner: root
        group: root

    - name: Créer le fichier .pgpoolkey dans le home de postgres
      ansible.builtin.copy:
        dest: /var/lib/postgresql/.pgpoolkey
        content: "{{ pgpoolkey }}"
        mode: 0600
        owner: postgres
        group: postgres

    - name: Ajouter les credentials dans pool_passwd
      ansible.builtin.command: pg_enc -m -f /etc/pgpool2/pgpool.conf -u k3s v9smN3iWpDtwb6eJbBcJ
      register: output
      changed_when: output.rc != 0
